version: "3.9"
services:

  ma-store:
    build: .
  db:
    ports:
      - "5433:5432"

  .adminer:
    image: adminer
    ports:
      - "8081:8080"
    networks:
      - db
    environment:
      - ADMINER_DESIGN=dracula

