version: "3.9"
services:
  ma-store:
    image: registry.master3.takima.io/mxue1/takima-store
    networks:
      - db
    depends_on:
      - db
    ports:
      - "8080:8080"
    env_file:
      - .env
    restart: on-failure
  db:
    image: postgres:15.2-alpine
    restart: unless-stopped
    networks:
      - db
    environment:
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD:-madmin}
      - POSTGRES_USER=${DATABASE_USER:-madmin}
      - POSTGRES_DB=${DATABASE_NAME:-ma-store-db}
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "sh -c 'pg_isready -U ${DATABASE_USER} -d ${DATABASE_NAME}'",
        ]
      interval: 10s
      timeout: 3s
      retries: 3

  flyway:
    image: flyway/flyway:9-alpine
    command: -connectRetries=60 -baselineVersion="0.0" baseline migrate info
    volumes:
      - ./db:/flyway/sql:ro
    environment:
      FLYWAY_URL: ${MA_DB_URL}
      FLYWAY_USER: ${DATABASE_USER}
      FLYWAY_PASSWORD: ${DATABASE_PASSWORD}
    depends_on:
      - db
    networks:
      - db
networks:
  db:
volumes:
  db-data:
