version: "3.9"
services:
  db:
    image: postgres:15.2-alpine
    restart: unless-stopped
    networks:
      - db
    environment:
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD:-madmin}
      - POSTGRES_USER=${DATABASE_USER:-madmin}
      - POSTGRES_DB=${DATABASE_NAME:-ma_store_db}
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./db:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "sh -c 'pg_isready -U ${DATABASE_USER} -d ${DATABASE_NAME}'",
        ]
      interval: 10s
      timeout: 3s
      retries: 3

#  flyway-db-webadmin:
#    image: adminer
#    container_name: ma-db-webadmin
#    restart: always
#    ports:
#      - 28080:8080
#    networks:
#      - db

  flyway:
    image: flyway/flyway:6.5.3-alpine
    command: -connectRetries=60 baseline migrate infopublic
    volumes:
      - ./flyway/sql:/flyway/sql
    env_file:
      .env
    depends_on:
      - db
    networks:
      - db
networks:
  db:
volumes:
  db-data:
