version: "3.9"
services:
  app:
    image: registry.master3.takima.io/acellasteibel/hibernate/back
    env_file:
      - .env
    networks:
      - network-db
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    restart: on-failure

  db:
    image: postgres:15.2-alpine
    restart: unless-stopped
    networks:
      - network-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD:-madmin}
      - POSTGRES_USER=${DATABASE_USER:-madmin}
      - POSTGRES_DB=${DATABASE_NAME:-ma_store_db}
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./db:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: pg_isready -U ${DATABASE_USER} -d ${DATABASE_NAME}
      interval: 10s
      timeout: 3s
      retries: 3

  flyway:
    image: flyway/flyway:9-alpine
    command: -connectRetries=60 -baselineVersion=0 baseline migrate info
    volumes:
      - ./flyway/sql:/flyway/sql:ro
    environment:
      FLYWAY_URL: $JDBC_URL
      FLYWAY_USER: $DATABASE_USER
      FLYWAY_PASSWORD: $DATABASE_PASSWORD
    depends_on:
      - db
    networks:
      - network-db

networks:
  network-db:

volumes:
  db-data:
