
.backend_cache_config:
  cache:
    paths:
      - .m2/repository
      - $MA_STORE/target/


.common_package_config:
  image:
    name: $KANIKO_IMAGE
    entrypoint: ['']
  stage: package
  before_script:
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
  rules:
    - if: $CI_COMMIT_BRANCH == "hibernate"
    - if: $CI_COMMIT_TAG
