spring:
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:52/ma_store_db}
    username: ${DATABASE_USER:madmin}
    password: ${DATABASE_PASSWORD:madmin}
  ## Logger
  output:
    ansi:
      enabled: always
jpa:
  properties:
    hibernate:
      jdbc:
        lob:
          non_contextual_creation: true
  hibernate:
    ddl-auto: validate


logging:
  level:
    root: warn
  pattern:
    console: '%d{dd-MM-yyyy HH:mm:ss.SSS} [%thread] %-5level %logger.%M - %msg%n'
    # enable debug traces

logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
