spring:
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:52/ma_store_db}
    username: ${DATABASE_USER:madmin}
    password: ${DATABASE_PASSWORD:madmin}
  ## Logger
  output:
    ansi:
      enabled: always


logging:
  level:
    root: debug
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
  pattern:
    console: '%d{dd-MM-yyyy HH:mm:ss.SSS} [%thread] %-5level %logger.%M - %msg%n'
